"""aggiunta scuola, citta, indirizzo e materia, rimosso user

Revision ID: 0e27747eaf24
Revises: ca05c0ba0c41
Create Date: 2025-10-17 14:52:35.119215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e27747eaf24'
down_revision: Union[str, Sequence[str], None] = 'ca05c0ba0c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=False),
    sa.Column('codice_postale', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citta_codice_postale'), 'citta', ['codice_postale'], unique=False)
    op.create_index(op.f('ix_citta_id'), 'citta', ['id'], unique=False)
    op.create_index(op.f('ix_citta_nome'), 'citta', ['nome'], unique=True)
    op.create_index(op.f('ix_citta_provincia'), 'citta', ['provincia'], unique=False)
    op.create_table('materie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materie_id'), 'materie', ['id'], unique=False)
    op.create_index(op.f('ix_materie_nome'), 'materie', ['nome'], unique=False)
    op.create_table('scuole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('indirizzo', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('sito_web', sa.String(), nullable=True),
    sa.Column('id_citta', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_citta'], ['citta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scuole_email'), 'scuole', ['email'], unique=False)
    op.create_index(op.f('ix_scuole_id'), 'scuole', ['id'], unique=False)
    op.create_index(op.f('ix_scuole_indirizzo'), 'scuole', ['indirizzo'], unique=False)
    op.create_index(op.f('ix_scuole_nome'), 'scuole', ['nome'], unique=False)
    op.create_index(op.f('ix_scuole_sito_web'), 'scuole', ['sito_web'], unique=False)
    op.create_index(op.f('ix_scuole_telefono'), 'scuole', ['telefono'], unique=False)
    op.create_index(op.f('ix_scuole_tipo'), 'scuole', ['tipo'], unique=False)
    op.create_table('indirizzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('id_scuola', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_scuola'], ['scuole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indirizzi_id'), 'indirizzi', ['id'], unique=False)
    op.create_index(op.f('ix_indirizzi_nome'), 'indirizzi', ['nome'], unique=False)
    op.create_table('association_table',
    sa.Column('indirizzo_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indirizzo_id'], ['indirizzi.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materie.id'], ),
    sa.PrimaryKeyConstraint('indirizzo_id', 'materia_id')
    )
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_table('association_table')
    op.drop_index(op.f('ix_indirizzi_nome'), table_name='indirizzi')
    op.drop_index(op.f('ix_indirizzi_id'), table_name='indirizzi')
    op.drop_table('indirizzi')
    op.drop_index(op.f('ix_scuole_tipo'), table_name='scuole')
    op.drop_index(op.f('ix_scuole_telefono'), table_name='scuole')
    op.drop_index(op.f('ix_scuole_sito_web'), table_name='scuole')
    op.drop_index(op.f('ix_scuole_nome'), table_name='scuole')
    op.drop_index(op.f('ix_scuole_indirizzo'), table_name='scuole')
    op.drop_index(op.f('ix_scuole_id'), table_name='scuole')
    op.drop_index(op.f('ix_scuole_email'), table_name='scuole')
    op.drop_table('scuole')
    op.drop_index(op.f('ix_materie_nome'), table_name='materie')
    op.drop_index(op.f('ix_materie_id'), table_name='materie')
    op.drop_table('materie')
    op.drop_index(op.f('ix_citta_provincia'), table_name='citta')
    op.drop_index(op.f('ix_citta_nome'), table_name='citta')
    op.drop_index(op.f('ix_citta_id'), table_name='citta')
    op.drop_index(op.f('ix_citta_codice_postale'), table_name='citta')
    op.drop_table('citta')
    # ### end Alembic commands ###
