"""rinonimata association table indirizi materie

Revision ID: 378befd7c561
Revises: 0e27747eaf24
Create Date: 2025-10-17 14:55:05.047703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378befd7c561'
down_revision: Union[str, Sequence[str], None] = '0e27747eaf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indirizzi_materie_table',
    sa.Column('indirizzo_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indirizzo_id'], ['indirizzi.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materie.id'], ),
    sa.PrimaryKeyConstraint('indirizzo_id', 'materia_id')
    )
    op.drop_table('association_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('indirizzo_id', sa.INTEGER(), nullable=False),
    sa.Column('materia_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['indirizzo_id'], ['indirizzi.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materie.id'], ),
    sa.PrimaryKeyConstraint('indirizzo_id', 'materia_id')
    )
    op.drop_table('indirizzi_materie_table')
    # ### end Alembic commands ###
