"""aggiunto campo regione Città

Revision ID: cc77d72cace4
Revises: 378befd7c561
Create Date: 2025-12-26 00:25:50.118501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc77d72cace4'
down_revision: Union[str, Sequence[str], None] = '378befd7c561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citta', sa.Column('regione', sa.String(), nullable=False, server_default=""))
    op.create_index(op.f('ix_citta_regione'), 'citta', ['regione'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citta_regione'), table_name='citta')
    op.drop_column('citta', 'regione')
    # ### end Alembic commands ###
